[HYEON] STEP 10 테스트 코드 작성
code-squad/javascript-vm pull request #81
Opened 2018-08-31 06:50 UTC by antaehyeon

1. jest 공식문서를 보고 개발하였습니다.
2. transfile 중 Babel 을 이용하여 개발하였습니다.
3. MVP 에 대한 테스트를 다양하게 적용하려고 시도하였습니다.
4. STEP10 에 대한 개발로그를 작성하였습니다.

2018-09-02 11:01 UTC, nigayo commented
일단 커밋로그는 무척 좋아요.

2018-09-02 12:03 UTC, crongro requested changes
수고하셨어요.
MVP를 테스트까지 하면서 더 이해가 높아졌기를 바랄게요.
잘했는데요, MOCK테스트를 조금 줄이는 방향으로 개선하면 좋겠어요.

2018-09-02 12:03 UTC, nigayo commented on Test/util.test.js
> +test("상품 선택이 올바른지 테스트합니다", () => {
설명은 좀더 구체적일수록 좋아요.
나중에 테스트결과를 쭉 살펴볼때 test함수의 첫번째 문장들만 모아 봐도 무슨테스트인지 알수 있을정도로요.

2018-09-02 12:03 UTC, nigayo commented on Test/wallet.test.js
> +    walletView.registerClickEventToInsertMoneyBtn = jest.fn();
mock을 너무 쉽게 쓰지 않도록 해보세요.
결국 테스트는 진짜를 테스트해야하고, 그럴 수 있는 부분은 그렇게 해보세요.

2018-10-07 05:29 UTC, antaehyeon commented on .babelrc
> +  "presets": ["es2015"]
- Babel is a toolchain that is mainly used to convert ECMAScript 2015+ code into a backwards compatible version of JavaScript in current and older browsers or environments.
- ES6/ES7 코드를 ECMAScript5 코드로 변환하기 위한 도구
- 다양한 작은 모듈들을 담는 일종의 `상자` 역할
- 코드를 컴파일하기 위해 작은 모듈들(presets)을 사용
- `babel-cli` 는 command line 를 사용할 수 있게 지원
- `.babelrc` 는 babel을 설정하기 위한 파일
- `proposal spec` 들이 존재함. 5개의 stage로 구분 (babel-preset-stage-0, 1, 2, 3, 4)
  - babel-preset-stage-4 = babel-preset-es2015
  - ~~한번에 사용할 수 있게 제공하는 것이 `babel-preset-env`~~
  - babel-preset-env 는 babel-preset-2015, 2016, 2017 를 대처한 것
- `babel-polyfill` 은 ES6 환경을 제공
  - polyfill 이란 code 조각으로 런타임에 존재하지 않는 native API의 복사본을 뜻함

2018-10-07 06:41 UTC, antaehyeon commented on Model/VendingMachineModel.js
> +    setProductVerificationTimerID(id) {
VendingMachineControlPresenter:43 에서 사용중이긴 한데, 모든 getter/setter가 필수로 필요하지 않다는 점 기억하겠습니다!

2018-10-07 07:07 UTC, antaehyeon commented on Presenter/VendingMachineWalletPresenter.js
> +VendingMachineWalletPresenter.prototype = {
prototype은 효과적으로 동작한다. new 를 통해 생성된 객체(인스턴스)들이 여러개 존재한다 하더라도, prototype에 연결된 객체들은 동일한 메모리 공간에서 효율적으로 재사용된다. 즉, 두 객체의 prototype 은 같으며, prototype 객체는 최상위 객체까지 연결되어 있어서, prototype 연결고리를 통해 객체간의 상속관계를 만들 수 있다.

- 출처 : 내 블로그 [STEP9](https://antaehyeon.github.io/devlog/2018/08/14/STEP9/)

2018-10-07 07:07 UTC, antaehyeon commented on README/step10.md
> +   Jest는 Facebook에서 React 애플리케이션을 포함한 모든 JavaScript 코드를 테스트하는 데 사용되며, Jest의 철학 중 하나는 통합 된 "zero-configuration"경험을 제공하는 것이다. 우리는 엔지니어가 즉시 사용 가능한 도구를 제공받을 때 더 많은 테스트를 작성하게되고 결과적으로 더 안정적이고 건강한 코드 기반을 얻게
이런 좋은 도구를 경험할 수 있게 해주셔서 감사합니다.

2018-10-07 07:38 UTC, antaehyeon commented on Test/control.test.js
> +const model = new Model();
참고하겠습니다.

2018-10-08 02:44 UTC, antaehyeon commented on Test/control.test.js
> +test("상품을 선택하는 버튼에 이벤트가 등록되는지 테스트한다", () => {
- `describe(name, fn)` creates a block that groups together several related tests in one "test suite".

2018-10-08 02:45 UTC, antaehyeon commented on Test/control.test.js
> +    // given
given - when - then 구조에 맞춰서 적용하려고 하니 테스트가 좀 더 수월했던 것 같습니다.
같은 구조에서도 경계가 모호한 테스트들이 있는데, 나중에 질문드리겠습니다!

2018-10-08 02:56 UTC, antaehyeon commented on Test/control.test.js
> +    const receivedResult = controlView.changeMoneyNodeTextContent(node, 10000);
이런 것들을 magic number 이라고 했던가요..
사용을 최대한 자제하겠습니다 👍

2018-10-08 02:59 UTC, antaehyeon commented on Test/control.test.js
> +    model.increaseInvestedMoney(7700);
확인하였습니다 👍

2018-10-08 03:01 UTC, antaehyeon commented on Test/control.test.js
> +    expect(setTimeout).toHaveBeenLastCalledWith(expect.any(Function), 1000);
감사합니다 👍

2018-10-08 03:04 UTC, antaehyeon commented on Test/control.test.js
> +    const price = 1000;
개인적으로 느꼈을 때, 천단위가 넘어가는 부분들은 제가 magic number 로 사용했던 것 같습니다.
피드백을 통해 앞으로 magic number 의 사용을 자제 하겠습니다

2018-10-08 13:17 UTC, antaehyeon commented on Test/log.test.js
> +it('로그 노드(DIV)를 정상적으로 삽입하는지 테스트합니다', () => {
수정하였습니다 👍

2018-10-09 03:41 UTC, antaehyeon commented on Test/log.test.js
> +    expect(logView.setNodeVisibility).toHaveBeenCalled();
수정하였습니다 👍

2018-10-09 03:52 UTC, antaehyeon commented on Test/util.test.js
> +    expect(refundModeResult).toBe("100원이 반환됨");
수정하였습니다 👍

2018-10-09 04:12 UTC, antaehyeon commented on Test/util.test.js
> +test("상품 선택이 올바른지 테스트합니다", () => {
구체적으로.. 알겠습니다 👍

2018-10-09 04:41 UTC, antaehyeon commented on Test/wallet.test.js
> +    walletView.registerClickEventToInsertMoneyBtn = jest.fn();
확인하였습니다.
그러면 click Event 에서는 보통 어떤식으로 테스트하나요?

2018-10-10 05:54 UTC, merged